valor = input('Digite algo: ')
print('O tipo do valor que você digitou é ',type(valor))
print('Só tem espaços? ', valor.isspace())
print('É um número? ', valor.isnumeric())
print('É alfabético? ', valor.isalpha())
print('É alfanumérico? ', valor.isalnum())
print('Está em maiúsculo? ', valor.isupper())
print('Está em minúsculo? ', valor.islower())
print('Está capitalizado? ', valor.istitle())
